### ISSUE TITLE
[TODO] Implement update password backend

### ISSUE THREAD

**Issue by Nithin-ELS** [Nithin-ELS/To-DoList#17]
Input :
- current password
- new password

case :
- current password should match
- new password should not be same as current password

**Comment by harsh31dangi** [comment]
Hi, can I work on this?

**Comment by Nithin-ELS** [comment]
> Hi, can I work on this?

Sure @harsh31dangi .

**Comment by harsh31dangi** [comment]
> Input :
> 
> * current password
> * new password
> 
> case :
> 
> * current password should match
> * new password should not be same as current password

Can you explain what do you mean by current password should match, like with what should it be matched?
